Document: cozy
Title: Debian cozy Manual
Author: <insert document author here>
Abstract: This manual describes what cozy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cozy/cozy.sgml.gz

Format: postscript
Files: /usr/share/doc/cozy/cozy.ps.gz

Format: text
Files: /usr/share/doc/cozy/cozy.text.gz

Format: HTML
Index: /usr/share/doc/cozy/html/index.html
Files: /usr/share/doc/cozy/html/*.html
