#!/bin/sh -e
# postinst script for cozy
#
# see: dh_installdeb(1)

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

# Use debconf.
. /usr/share/debconf/confmodule

case "$1" in
    configure|reconfigure)
	COZY_DOMAIN=
	db_get cozy/fqdn || true
	COZY_DOMAIN=$RET

	echo "Chosen domain name for Cozy: $COZY_DOMAIN"

	echo 'Installing NPM dependencies...'
        [ ! -d /usr/local/lib/node_modules/cozy-controller ] && npm install -g cozy-controller
        [ ! -d /usr/local/lib/node_modules/cozy-monitor ] && npm install -g cozy-monitor

	echo 'Creating UNIX users...'
        id cozy >/dev/null 2>&1 || useradd -M cozy
        id cozy-data-system >/dev/null 2>&1 || useradd -M cozy-data-system
        id cozy-home >/dev/null 2>&1 || useradd -M cozy-home

	echo 'Generating CouchDB tokens...'
        [ ! -d /etc/cozy ] && mkdir /etc/cozy
        chown -hR cozy /etc/cozy
        if [ ! -f /etc/cozy/couchdb.login ]; then
                pwgen -1 > /etc/cozy/couchdb.login && \
                pwgen -1 >> /etc/cozy/couchdb.login
                while ! curl -s 127.0.0.1:5984 >/dev/null; do echo "Waiting for CouchDB to start..."; sleep 5; done
                curl -s -X PUT 127.0.0.1:5984/_config/admins/$(head -n1 /etc/cozy/couchdb.login) -d "\"$(tail -n1 /etc/cozy/couchdb.login)\""
        fi
        chown cozy-data-system /etc/cozy/couchdb.login
        chmod 640 /etc/cozy/couchdb.login

	echo 'Configuring Cozy Indexer...'
        if [ ! -d /var/lib/cozy-indexer ]; then
                mkdir -p /var/lib/cozy-indexer && \
                chown -R cozy:cozy /var/lib/cozy-indexer
        fi
	CONFIGFILE=/etc/supervisor/conf.d/cozy-indexer.conf
	if [ -f $CONFIGFILE ]; then
		BEFORE=`sha1sum $CONFIGFILE`
	else
		BEFORE=
	fi
	ucf --three-way --debconf-ok /usr/share/cozy/supervisor-cozy-indexer $CONFIGFILE
	AFTER=`sha1sum $CONFIGFILE`
	if [ "$BEFORE" != "$AFTER" ]; then
		supervisorctl reload
	fi
	while ! curl -s 127.0.0.1:9102/ >/dev/null; do echo "Waiting for Cozy Indexer to start..."; sleep 5; done

	echo 'Configuring Cozy Controller...'
	CONFIGFILE=/etc/supervisor/conf.d/cozy-controller.conf
	if [ -f $CONFIGFILE ]; then
		BEFORE=`sha1sum $CONFIGFILE`
	else
		BEFORE=
	fi
	ucf --three-way --debconf-ok /usr/share/cozy/supervisor-cozy-controller $CONFIGFILE
	AFTER=`sha1sum $CONFIGFILE`
	if [ "$BEFORE" != "$AFTER" ]; then
		supervisorctl reload
	fi
        while ! curl -s 127.0.0.1:9102 >/dev/null; do echo "Waiting for Cozy Controller to start..."; sleep 5; done

	echo 'Installing Cozy Platform apps...'
        if [ ! -d /usr/local/cozy/apps/data-system ]; then
                cozy-monitor install-cozy-stack
        fi
        if [ ! -d /usr/local/cozy/apps/home ]; then
                cozy-monitor install home
        fi
        if [ ! -d /usr/local/cozy/apps/proxy ]; then
                cozy-monitor install proxy
        fi

	echo 'Generating SSL keys and certificates...'
        if [ ! -f /etc/cozy/dh.pem ]; then
                openssl dhparam -out /etc/cozy/dh.pem -outform PEM -2 2048
                chmod 400 /etc/cozy/dh.pem
        fi
        if [ ! -f /etc/cozy/server.key ]; then
                openssl req -x509 -nodes -newkey rsa:2048 -keyout /etc/cozy/server.key -out /etc/cozy/server.crt -days 3650 -subj "/CN=$COZY_DOMAIN"
                chmod 400 /etc/cozy/server.key
        fi

        if [ -d /etc/nginx ]; then
		echo 'Configuring Nginx...'
		if [ -f /etc/nginx/sites-enabled/default ]; then
			rm /etc/nginx/sites-enabled/default
		fi
		TMPFILE=`mktemp`
		CONFIGFILE=/etc/nginx/conf.d/cozy.conf
		if [ -f $CONFIGFILE ]; then
			BEFORE=`sha1sum $CONFIGFILE`
		else
			BEFORE=
		fi
		sed "s/%COZY_DOMAIN%/$COZY_DOMAIN/" /usr/share/cozy/nginx-config > $TMPFILE
		ucf --three-way --debconf-ok $TMPFILE $CONFIGFILE
		rm $TMPFILE
		AFTER=`sha1sum $CONFIGFILE`
		if [ "$BEFORE" != "$AFTER" ]; then
			service nginx status >/dev/null 2>&1 && service nginx reload
		fi
		nginx -t && echo "Cozy installation done!"
	elif [ -f /etc/apache2/apache2.conf ]; then
		echo 'Configuring Apache2...'
		a2enmod ssl
		a2enmod proxy_http
		TMPFILE=`mktemp`
		CONFIGFILE=/etc/apache2/sites-available/cozy.conf
		if [ -f $CONFIGFILE ]; then
			BEFORE=`sha1sum $CONFIGFILE`
		else
			BEFORE=
		fi
		sed "s/%COZY_DOMAIN%/$COZY_DOMAIN/" /usr/share/cozy/apache-config > $TMPFILE
		ucf --three-way --debconf-ok $TMPFILE $CONFIGFILE
		rm $TMPFILE
		if [ ! -f /etc/apache2/sites-enabled/cozy.conf ]; then
			BEFORE=
			ln -s /etc/apache2/sites-available/cozy.conf /etc/apache2/sites-enabled/cozy.conf
		fi
		AFTER=`sha1sum $CONFIGFILE`
		if [ "$BEFORE" != "$AFTER" ]; then
			apachectl configtest && apachectl restart
		fi
		apachectl configtest && echo "Cozy installation done!"
	else
		echo "May be you missed to install an http server"
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
